### ISSUE TITLE
Basic Editor

### ISSUE THREAD

**Issue by apeltsi** [apeltsi/loitsu#21]
# Task list

- [x] Get loitsu working alongside SolidJS
- [x] Feature for disabling most of the runtime ECS features. (Ticks, Frames, Start methods)
- [x] ECS event system, the editor should be able to register functions to listen for ECS events. Such as when the ECS tree updates, or an entity is updated
- [x] Direct Asset loader. Load assets directly from a local server.
- [x] Asset server. A local server that simply hosts all assets needed by the editor. This server will also update local files if the editor so desires. 
- [x] Entity component details fetch
- [x] Camera Movement
- [x] Camera Zoom
- [x] Entity component details update
- [x] Entity Inspector
- [x] Hierarchy
- [x] Entity move tool
- [x] Scene chooser startup arg
- [x] Scene serialization
